name: Nuke AWS Account
description: Job to Nuke an AWS Account
title: "[Nuke]: "
labels: ["nuke"]
assignees:
  - octocat

body:
  - type: markdown
    attributes:
      value: |
        **Please complete the following form to use the AWS Nuke Servie**
  - type: input
    attributes:
      label: Account to Nuke AWS Services
      description: Enter the account number from which you want to nuke AWS Services
    validations:
      required: true
  - type: input
    attributes:
      label: Account Alias
      description: Enter the account Alias for which you want to nuke AWS Services
    validations:
      required: true
  - type: input
    attributes:
      label: Regions
      description: Region
      multiple: true
      options:
        - us-east-1
        - us-east-2
        - us-west-1
        - us-west-2
    validations:
      required: true
  - type: input
    attributes:
      label: Excluded Resources
      description: Excluded Resources
    validations:
      required: false
  - type: input
    attributes:
      label: Included Resources
      description: Included Resources
    validations:
      required: false

