name: Nuke AWS Account
description: Job to Nuke an AWS Account
title: "[Nuke]: "

body:
  - type: markdown
    attributes:
      value: |
        **Please complete the following form to use the AWS Nuke Servie**
  