name: Nuke AWS Account
description: Job to Nuke an AWS Account
title: "[Nuke]: "
labels: ["nuke"]
assignees:
  - octocat

body:
  - type: markdown
    attributes:
      value: |
        **Please complete the following form to use the AWS Nuke Servie. By default all the resources in the regions specified will be nuked. If you specify Target Resources, only those resources will be nuked. If you specify Excluded Resources, then everything else but those excluded resources will be nuked**

  - type: input
    id: account_tonuke
    attributes:
      label: Account to Nuke AWS Services
      description: Enter the account number from which you want to nuke AWS Services
      placeholder: "381492150661"

  - type: dropdown
    id: nuke-resources
    attributes:
      label: Nuke Resources?
      description: By Default - It will run a dry-run and won't nuke resources. Select Yes below to actually nuke resources
      multiple: false
      options:
        - "No"
        - "Yes"
      default: 0
