name: Nuke AWS Account
description: Job to Nuke an AWS Account
title: "[Nuke]: "
labels: ["nuke"]
assignees:
  - octocat

body:
  - type: markdown
    attributes:
      value: |
        **Please complete the following form to use the AWS Nuke Servie**
  - type: input
    attributes:
      label: Account to Nuke AWS Services
      description: Enter the account number from which you want to nuke AWS Services
  - type: input
    attributes:
      label: Account Alias
      description: Enter the account Alias for which you want to nuke AWS Services
