name: Nuke AWS Account
description: Job to Nuke an AWS Account
title: "[Nuke]: "
labels: ["nuke"]
assignees:
  - octocat

body:
  - type: markdown
    attributes:
      value: |
        **Please complete the following form to use the AWS Nuke Servie**
  - type: input
    id: account_tonuke
    attributes:
      label: Account to Nuke AWS Services
      description: Enter the account number from which you want to nuke AWS Services
    validations:
      required: true
  - type: input
    id: accountalias_tonuke
    attributes:
      label: Account Alias
      description: Enter the account Alias for which you want to nuke AWS Services
    validations:
      required: true
  - type: checkboxes
    id: regions
    attributes:
      label: Regions
      description: Region
      options:
        - label: us-east-1
        - label: us-east-2
        - label: us-west-1
        - label: us-west-2
  - type: input
    id: excluded_resources
    attributes:
      label: Excluded Resources
      description: Excluded Resources
    validations:
      required: false
  - type: input
    id: included_resources
    attributes:
      label: Included Resources
      description: Included Resources
    validations:
      required: false

