name: Nuke AWS Account
description: Job to Nuke an AWS Account
title: "[Nuke]: "
labels: ["nuke"]
assignees:
  - octocat

body:
  - type: markdown
    attributes:
      value: |
        **Please complete the following form to use the AWS Nuke Servie. Enter Account Number. Default account number would be 381492150661**

  - type: input
    id: account_tonuke
    attributes:
      label: Account to Nuke AWS Services
      description: Enter the account number from which you want to nuke AWS Services
      placeholder: "381492150661"

  - type: dropdown
    id: nuke-resources
    attributes:
      label: Do you want to run Dry Run or actually Nuke Resources? 
      description: Select Default option No for Dry Run. Select Yes below to actually nuke resources
      multiple: false
      options:
        - "No"
        - "Yes"
      default: 0
