name: Dhruv Test Workflow

on:
  issues:
    types:
      - opened
  push:
    branches:
      - main

jobs:
  aws-nuke:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Download and Extract 
        run: |
          mkdir -p aws-nuke
          wget -c https://github.com/rebuy-de/aws-nuke/releases/download/v2.25.0/aws-nuke-v2.25.0-linux-amd64.tar.gz -O - | tar -xz -C aws-nuke
          ./aws-nuke/aws-nuke-v2.25.0-linux-amd64 --help


      - name: AWS CLI Test
        run: |
          aws s3 ls 
          ls -la 
          ls -la config/
          ls -la ./aws-nuke/
          
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-west-2'


      - name: Run aws-nuke
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-west-2'
        run: | 
          nuke_resources="No"
          echo -e $nuke_resources

          if [ ${nuke_resources} == "Yes" ]
          then
            echo "Running AWS Nuke. This will delete resources"
          else
            echo "Running AWS Nuke. This will be a DRY RUN" 
            ./aws-nuke/aws-nuke-v2.25.0-linux-amd64 -c ./config/nuke-config.yml --force --force-sleep 1 > ./aws-nuke/output.txt
            cat ./aws-nuke/output.txt
          fi

      - name: Create CSV File
        run: |
          echo "Creating CSV File"
          echo -e 'Region,Resource type,Resource name,Tags,Comments' > ./aws-nuke/aws-nuke.csv
          cat ./aws-nuke/output.txt | grep -v -e 'aws-nuke' -e 'Do you really' -e 'Waiting 3s before continuing' -e 'Scan complete' -e 'The above resources would be deleted with the supplied configuration' -e 'Nuke complete' -e '^$'| sed 's/ - /,/g' >> ./aws-nuke/aws-nuke.csv
          cat ./aws-nuke/aws-nuke.csv