name: Dhruv Test Workflow

on:
  issues:
    types:
      - opened

jobs:
  aws-nuke:
    runs-on: ubuntu-latest
    steps:
      - name: Log Event Payload
        run: |
          payload_body="${{ github.event.issue.body }}"
          echo "$payload_body"
          echo account_tonuke