name: Dhruv Test Workflow

on:
  issues:
    types:
      - opened
  push:
    branches:
      - main

jobs:
  aws-nuke:
    runs-on: ubuntu-latest
    steps:

      - name: Download and Extract 
        run: |
          mkdir -p aws-nuke
          wget -c https://github.com/rebuy-de/aws-nuke/releases/download/v2.25.0/aws-nuke-v2.25.0-linux-amd64.tar.gz -O - | tar -xz -C aws-nuke
          ./aws-nuke/aws-nuke-v2.25.0-linux-amd64 --help


      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2                         # default
          verbose: false                     # default
          arch: amd64 


      - name: AWS CLI Test
        run: |
          aws s3 ls 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-west-2'


      - name: Run aws-nuke
        run: | 
          payload_body="${{ github.event.issue.body }}"
          nuke_resources=$(echo "$payload_body" | grep -A2 "### Nuke Resources" | tail -n1)

          if [ ${nuke_resources} == "Yes" ]
          then
            echo "Running AWS Nuke. This will delete resources"
          else
            echo "Running AWS Nuke. This will be a DRY RUN" 
          fi