name: Dhruv Test Workflow

on:
  issues:
    types:
      - opened

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Log Event Payload
        run: echo "$GITHUB_EVENT_PATH"
          