name: Dhruv Test Workflow

on:
  issues:
    types:
      - opened
  # push:
  #   branches:
  #     - main

jobs:
  aws-nuke:
    runs-on: ubuntu-latest
    steps:
      - name: Create Config File for aws-nuke
        run: |

          payload_body="${{ github.event.issue.body }}"
          #echo "$payload_body"
          
          account=$(echo "$payload_body" |grep -A2 "### Account to Nuke AWS Services" | tail -n1)
          echo $account

          excluded_resources=$(echo "$payload_body" |grep -A2 "### Excluded Resources" | tail -n1)
          echo $excluded_resources

          target_resources=$(echo "$payload_body" |grep -A2 "### Target Resources" | tail -n1)
          echo $target_resources
          
          aws_regions=$(echo "$payload_body" | grep -A2 "### Regions" | tail -n1)
          echo $aws_regions
          
          nuke_resources=$(echo "$payload_body" | grep -A2 "### Nuke Resources" | tail -n1)
          echo $nuke_resources
          
          mkdir -p aws-nuke

          echo -e "regions:\n - global" > ./aws-nuke/aws-nuke-config.yaml

          for each in $aws_regions
            do 
              echo -e " - $each"  >> ./aws-nuke/aws-nuke-config.yaml
            done

          echo "" >> ./aws-nuke/aws-nuke-config.yaml

          echo -e "account-blacklist:\n- 631346502955\n- 771427977398\n- 294630680963\n- 065651352966\n- 149321076751\n- 306340782601\n- 320460626817\n- 418340538962\n- 609794691195\n- 831452073949\n- 902262931558" >> ./aws-nuke/aws-nuke-config.yaml

          echo "" >> ./aws-nuke/aws-nuke-config.yaml

          echo -e "resource-types:\n targets:" >> ./aws-nuke/aws-nuke-config.yaml

          for each in $target_resources
            do 
              echo -e " - $each"  >> ./aws-nuke/aws-nuke-config.yaml
            done

          echo -e "\n excludes:" >> ./aws-nuke/aws-nuke-config.yaml

          for each in $excluded_resources
            do 
              echo -e " - $each"  >> ./aws-nuke/aws-nuke-config.yaml
            done

          echo "" >> ./aws-nuke/aws-nuke-config.yaml

          echo -e "accounts:" >> ./aws-nuke/aws-nuke-config.yaml

          cat ./aws-nuke/aws-nuke-config.yaml

          ls -la ./aws-nuke/


      - name: Download and Extract 
        run: |
          mkdir -p aws-nuke
          wget -c https://github.com/rebuy-de/aws-nuke/releases/download/v2.25.0/aws-nuke-v2.25.0-linux-amd64.tar.gz -O - | tar -xz -C aws-nuke
          ./aws-nuke/aws-nuke-v2.25.0-linux-amd64 --help


      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2                         # default
          verbose: false                     # default
          arch: amd64 


      - name: AWS CLI Test
        run: |
          aws s3 ls 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-west-2'


      - name: Run aws-nuke
        run: | 
          nuke_resources=$(echo "$payload_body" | grep -A2 "### Nuke Resources" | tail -n1)
          echo $nuke_resources
          echo $nuke_resources


  