name: Dhruv Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Echo hello world
        run: echo "Hello World"
        shell: bash

  goodbye:
    steps:
      - name: Goodbye World!
        run: echo "Good Bye World!"
        shell: bash